### ISSUE TITLE
Design socket.io events for game-lifecycle

### ISSUE THREAD

**Issue by Fr3dric0** [Strooped/strooped-relay#3]
- [ ] Which events to implement to solve each problem
- [ ] How to format these events

**Comment by nerok** [comment]
Game Master needs in the lobby to:
- [ ] Send: a task is beginning (which task is specified by GM)
- [ ] Send: the game is ending
- [ ] Receive: a player has joined (including info about the user)

Game Master needs in the task view to:
- [ ] Receive: The players has answered, with their answers
- [ ] Send: Task has timed out
- [ ] Send: a task is beginning (might be same as in lobby)
